update vendor-assets.json to say Doomtown instead of AGOT
mmeldo/townsquare pull request #61
Opened 2021-03-03 15:39 UTC by AaronSchnabel

I've updated vendor-assets.json to say Doomtown instead of A Game of Thrones

2021-03-04 08:47 UTC, mmeldo requested changes
Just trying the review process 😄

2021-03-04 08:47 UTC, mmeldo commented on vendor-assets.json
> +<!DOCTYPE html><html><head><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="description" cont
```suggestion
<!DOCTYPE html><html><head><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="description" content="Play Doomtown in your browser"><link rel="apple-touch-icon" sizes="76x76" href="/apple-touch-icon.png"><link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png"><link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png"><link rel="manifest" href="/site.webmanifest"><link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5"><meta name="msapplication-TileColor" content="#da532c"><meta name="theme-color" content="#ffffff"><title>The Town Square - Play Doomtown in your browser</title><link href="/bundle.css" rel="stylesheet"></head><body><div id="component"></div><script>(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
```

2021-03-08 15:04 UTC, AaronSchnabel reviewed
I think the change looks good.

2021-03-09 19:52 UTC, mmeldo approved these changes

2021-03-09 19:53 UTC, merged